# Generated by Django 5.2.8 on 2025-11-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('form_received', 'Form Successfully Received'), ('form_incomplete', 'Form Missing Required Fields'), ('form_invalid', 'Form Invalid Format'), ('help', 'Help Command'), ('welcome', 'Welcome Message')], max_length=50, unique=True)),
                ('message_template', models.TextField(help_text='Use {name}, {project}, etc. for placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Response',
                'verbose_name_plural': 'Bot Responses',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to process messages from this group')),
                ('auto_reply', models.BooleanField(default=True, help_text='Send confirmation when form is received')),
                ('require_all_fields', models.BooleanField(default=False, help_text='Require all fields or just name+project')),
                ('total_forms_received', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Group',
                'verbose_name_plural': 'WhatsApp Groups',
            },
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('project', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.CharField(blank=True, default='', max_length=255)),
                ('teacher', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('lesson_titles', models.TextField(blank=True, default='')),
                ('lesson_references', models.TextField(blank=True, default='')),
                ('whatsapp_message_id', models.CharField(max_length=255, unique=True)),
                ('whatsapp_from', models.CharField(help_text="Sender's WhatsApp number", max_length=50)),
                ('whatsapp_timestamp', models.DateTimeField()),
                ('group_id', models.CharField(blank=True, default='', help_text='WhatsApp group ID if from group', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('raw_message', models.TextField(help_text='Original message text')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Parser confidence 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intake Form',
                'verbose_name_plural': 'Intake Forms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bot_intakef_status_8580b1_idx'), models.Index(fields=['whatsapp_from'], name='bot_intakef_whatsap_afaffe_idx'), models.Index(fields=['created_at'], name='bot_intakef_created_e50c72_idx'), models.Index(fields=['school'], name='bot_intakef_school_0af987_idx'), models.Index(fields=['project'], name='bot_intakef_project_9304eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=50)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('is_group_message', models.BooleanField(default=False)),
                ('group_id', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_type', models.CharField(choices=[('intake_form', 'Intake Form'), ('chat', 'Regular Chat'), ('media', 'Media/Attachment'), ('reaction', 'Reaction'), ('system', 'System Message'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('content', models.TextField()),
                ('was_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='bot.intakeform')),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['message_type'], name='bot_message_message_bca7eb_idx'), models.Index(fields=['from_number'], name='bot_message_from_nu_cd9cd8_idx'), models.Index(fields=['timestamp'], name='bot_message_timesta_bc8847_idx'), models.Index(fields=['was_processed'], name='bot_message_was_pro_0f791a_idx')],
            },
        ),
    ]
